<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>source.gtrpge</string>

        <key>fileTypes</key>
        <array>
            <string>src</string>
        </array>

        <key>name</key>
        <string>GTRPGE Source File</string>

        <key>patterns</key>
        <array>
            <dict>
                <key>match</match>
                <string>//.*$</string>
                <key>name</key>
                <string>comment.line.character</string>
            </dict>

            <dict>
                <key>match</key>
                <string>\b(?i:(if|while|do_while|print|label|proc|continue|break))\b</string>
                <key>name</key>
                <string>keyword.control</string>
            </dict>

            <dict>
                <key>match</key>
                <string>#?(?i:(function|object|declare|asm_function))\b</string>
                <key>name</key>
                <string>keyword.other</string>
            </dict>

            <dict>
                <key>match</match>
                <string>(-|\b)[0-9]+\b</string>
                <key>name</key>
                <string>constant.numeric</string>
            </dict>

            <dict>
                <key>begin</match>
                <string>"</string>
                <key>end</match>
                <string>"</string>
                <key>name</key>
                <string>string.quoted.double</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>constant.character.escape.untitled</string>
                        <key>match</key>
                        <string>\\.</string>
                    </dict>
                </array>
            </dict>

            <dict>
                <key>begin</match>
                <string>'</string>
                <key>end</match>
                <string>'</string>
                <key>name</key>
                <string>string.quoted.single</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>constant.character.escape.untitled</string>
                        <key>match</key>
                        <string>\\.</string>
                    </dict>
                </array>
            </dict>

            <dict>
                <key>match</match>
                <string>\b(?:(return|push_0|push_1|push_none|push_8|push_16|push_32|store|say_uf|say|say_unsigned|say_char|pop|stack_dup|stack_peek|stack_size|call|get_prop|has_prop|set_prop|get_item|has_item|get_size|set_item|del_item|add_item|typeof|astype|eq|neq|jmp|jz|jnz|lt|lte|gt|gte|not|add|sub|mult|div|mod|pow|left_shift|right_shift|bit_and|bit_or|bit_xor|bit_not|random|get_random|get_keys|stack_swap|get_setting|set_setting|get_key|get_option|get_line|add_option|add_option_x|strcpy|strcat|strlen|strcmp|error|add_page|del_page|end_page|new|is_static))\b</string>
                <key>name</key>
                <string>constant.language</string>
            </dict>
            <!--
            <dict>
                <key>match</match>
                <string>(=|~|<|>|\+|-|\*|/|\?|\+\+)</string>
                <key>name</key>
                <string>keyword.operator</string>
            </dict>
                -->

        </array>
        <key>uuid</key>
        <string>4e63b622-9001-11e7-abc4-cec278b6b50a</string>
    </dict>
</plist>